baseURL = "https://rvteja92.github.io/pathak/"
languageCode = "en-us"
title = "Pathak"
theme = "tale"
publishDir = "docs"

[Author]
    name = "Ravi Teja P"
    homepage = "https://rvteja92.github.io/"